# Compose web services.
version: "3"
services:
  botdb:
    image: stevepryde/sp:naughts_botdb
    build:
      context: .
      dockerfile: ./docker/botdb.dockerfile
    restart: unless-stopped
    ports:
      - "5008:5008"
    environment:
      NAUGHTS_DB: "naughts:naughts@postgres:5432/naughts"
