# Compose web services.
version: "3"
services:
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: naughts
      POSTGRES_PASSWORD: naughts
  gameservice:
    image: stevepryde/sp:naughts_gameservice
    build:
      context: .
      dockerfile: ./docker/gameservice.dockerfile
    restart: unless-stopped
    ports:
      - "5009:5009"
    environment:
      NAUGHTS_DB: "naughts:naughts@postgres:5432/naughts"
      NODE_ENV: "production"
